### ISSUE TITLE
`develop` Sort Order Issues

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#262]
```
Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'sort_order' in order clause is ambiguous
The SQL being executed was: SELECT EXISTS(SELECT `wiki_page`.* FROM `wiki_page` LEFT JOIN `content`
ON `wiki_page`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id`
LEFT JOIN `user` ON `content`.`created_by` = `user`.`id`
LEFT JOIN `space` ON contentcontainer.pk=space.id
AND contentcontainer.class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer.pk=cuser.id AND contentcontainer.class='humhub\\modules\\user\\models\\User' LEFT JOIN `space_membership` ON contentcont


Stack trace:
#0 /srv/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /srv/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /srv/humhub/protected/vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal()
#3 /srv/humhub/protected/vendor/yiisoft/yii2/db/Query.php(446): yii\db\Command->queryScalar()
#4 /srv/www/htdocs/leandraa/modules/wiki/models/WikiPage.php(536): yii\db\Query->exists()
#5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Component.php(139): humhub\modules\wiki\models\WikiPage->getIsCategory()
#6 /srv/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get()
#7 /srv/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(210): yii\db\BaseActiveRecord->__get()
#8 /srv/www/htdocs/leandraa/modules/wiki/widgets/PageListItemTitle.php(76): humhub\modules\content\components\ContentActiveRecord->__get()
#9 /srv/humhub/protected/humhub/components/Widget.php(63): humhub\modules\wiki\widgets\PageListItemTitle->run()
#10 /srv/www/htdocs/leandraa/modules/wiki/widgets/views/categoryListItem.php(33): humhub\components\Widget::widget()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/srv/www/htdocs...')
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#14 /srv/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render()
#15 /srv/www/htdocs/leandraa/modules/wiki/widgets/CategoryListItem.php(127): yii\base\Widget->render()
#16 /srv/humhub/protected/humhub/components/Widget.php(63): humhub\modules\wiki\widgets\CategoryListItem->run()
#17 /srv/www/htdocs/leandraa/modules/wiki/widgets/views/categoryListView.php(25): humhub\components\Widget::widget()
#18 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/srv/www/htdocs...')
#19 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#20 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#21 /srv/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render()
#22 /srv/www/htdocs/leandraa/modules/wiki/widgets/CategoryListView.php(97): yii\base\Widget->render()
#23 /srv/humhub/protected/humhub/components/Widget.php(63): humhub\modules\wiki\widgets\CategoryListView->run()
#24 /srv/www/htdocs/leandraa/modules/wiki/widgets/views/wikiSidebar.php(39): humhub\components\Widget::widget()
```

**Comment by yurabakhtin** [comment]
@luke- Fixed in the commit https://github.com/humhub/wiki/pull/249/commits/0ccc57503b45574c49f91ede07054b8424433cfe of the PR https://github.com/humhub/wiki/pull/249. Please let me know if we should do a fix for the `master` branch.

**Comment by funkycram** [comment]
Thanks @yurabakhtin ! I don't think we need a fix on the `master` branch as this issue is concerning Humhub 1.15 because of adding `sorter_order` on the Space model.

**Comment by yurabakhtin** [comment]
@funkycram Ah yes, you are right, thanks.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the fast fix. Can you please check for other `sort_order` uses without prefix?

**Comment by yurabakhtin** [comment]
@luke- I have reviewed all other modules where column `sort_order` is used wihout table prefix but cannot see the error, so I don't think we should add the prefix there.
