### ISSUE TITLE
Error on `develop`

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#272]
```
yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\wiki\widgets\WikiRichText::maxLength in /srv/humhub/protected/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#1 /srv/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#2 [internal function]: yii\base\BaseObject->__construct()
#3 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#4 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#5 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#6 /srv/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject()
#7 /srv/humhub/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(293): humhub\components\Widget::widget()
#8 /srv/www/htdocs/community/modules/wiki/widgets/views/wallEntry.php(20): humhub\modules\content\widgets\richtext\AbstractRichText::output()
#9 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/srv/www/htdocs...')
#10 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render()
#13 /srv/www/htdocs/community/modules/wiki/widgets/WallEntry.php(75): yii\base\Widget->render()
#14 /srv/humhub/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(226): humhub\modules\wiki\widgets\WallEntry->renderContent()
#15 /srv/humhub/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody()
#16 /srv/humhub/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run()
#17 [internal function]: humhub\components\Widget::widget()
#18 /srv/humhub/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func()
#19 /srv/humhub/protected/humhub/modules/stream/actions/StreamEntryResponse.php(81): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry()
#20 /srv/humhub/protected/humhub/modules/stream/actions/Stream.php(414): humhub\modules\stream\actions\StreamEntryResponse::getAsArray()
#21 /srv/humhub/protected/humhub/modules/stream/actions/Stream.php(369): humhub\modules\stream\actions\Stream->getStreamEntryResult()
#22 /srv/humhub/protected/humhub/modules/stream/actions/Stream.php(348): humhub\modules\stream\actions\Stream->addResponseEntries()
#23 [internal function]: humhub\modules\stream\actions\Stream->run()
#24 /srv/humhub/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array()
#25 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams()
#26 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#27 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#28 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#29 /srv/www/htdocs/community/index.php(24): yii\base\Application->run()
#30 {main}
```

**Comment by luke-** [comment]
@yurabakhtin I think this is related to the recent deprecation cleanups?
